# Lab | Data Aggregation and Filtering

In this challenge, we will continue to work with customer data from an insurance company. We will use the dataset called marketing_customer_analysis.csv, which can be found at the following link:

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis.csv

This dataset contains information such as customer demographics, policy details, vehicle information, and the customer's response to the last marketing campaign. Our goal is to explore and analyze this data by first performing data cleaning, formatting, and structuring.

1. Create a new DataFrame that only includes customers who:
   - have a **low total_claim_amount** (e.g., below $1,000),
   - have a response "Yes" to the last marketing campaign.

2. Using the original Dataframe, analyze:
   - the average `monthly_premium` and/or customer lifetime value by `policy_type` and `gender` for customers who responded "Yes", and
   - compare these insights to `total_claim_amount` patterns, and discuss which segments appear most profitable or low-risk for the company.

3. Analyze the total number of customers who have policies in each state, and then filter the results to only include states where there are more than 500 customers.

4. Find the maximum, minimum, and median customer lifetime value by education level and gender. Write your conclusions.

## Bonus

5. The marketing team wants to analyze the number of policies sold by state and month. Present the data in a table where the months are arranged as columns and the states are arranged as rows.

6.  Display a new DataFrame that contains the number of policies sold by month, by state, for the top 3 states with the highest number of policies sold.

*Hint:*
- *To accomplish this, you will first need to group the data by state and month, then count the number of policies sold for each group. Afterwards, you will need to sort the data by the count of policies sold in descending order.*
- *Next, you will select the top 3 states with the highest number of policies sold.*
- *Finally, you will create a new DataFrame that contains the number of policies sold by month for each of the top 3 states.*

7. The marketing team wants to analyze the effect of different marketing channels on the customer response rate.

Hint: You can use melt to unpivot the data and create a table that shows the customer response rate (those who responded "Yes") by marketing channel.

External Resources for Data Filtering: https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9

In [2]:
import pandas as pd

url = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis.csv"

table_mkt = pd.read_csv(url)

table_mkt.head()

,Unnamed: 0,Customer,State,Customer Lifetime Value,Response,Coverage,Education,Effective To Date,EmploymentStatus,Gender,...,Number of Open Complaints,Number of Policies,Policy Type,Policy,Renew Offer Type,Sales Channel,Total Claim Amount,Vehicle Class,Vehicle Size,Vehicle Type
0,0,DK49336,Arizona,4809.216960,No,Basic,College,2/18/11,Employed,M,...,0.0,9,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medsize,NaN
1,1,KX64629,California,2228.525238,No,Basic,College,1/18/11,Unemployed,F,...,0.0,1,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medsize,NaN
2,2,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2/10/11,Employed,M,...,0.0,2,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medsize,A
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,1/11/11,Employed,M,...,0.0,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A
4,4,QA50777,Oregon,9025.067525,No,Premium,Bachelor,1/17/11,Medical Leave,F,...,NaN,7,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medsize,NaN

In [3]:
condition_1 = table_mkt["Total Claim Amount"] < 1000

condition_2 = table_mkt["Response"] == "Yes"

In [4]:
table_mkt_filtered = table_mkt[
    (table_mkt["Total Claim Amount"] < 1000) &
    (table_mkt["Response"] == "Yes")
]

In [ ]:
#NOS QUEDAMOS SOLO CON LAS COLUMNAS YES

table_mkt_yes = table_mkt[table_mkt["Response"] == "Yes"]

In [7]:
#AGRUPAMOS POR DOS COLUMNAS : POLICY TYPE Y GENDER

table_mkt_yes.groupby(["Policy Type", "Gender"])

In [8]:
#CALCULAMOS LAS MEDIAS DE LAS TRES COLUMNAS

analysis = table_mkt_yes.groupby(
    ["Policy Type", "Gender"]
)[
    [
        "Monthly Premium Auto",
        "Customer Lifetime Value",
        "Total Claim Amount"
    ]
].mean()

In [9]:
analysis = analysis.round(2)

analysis

                       Monthly Premium Auto  Customer Lifetime Value  \
Policy Type    Gender
Corporate Auto F                      94.30                  7712.63
               M                      92.19                  7944.47
Personal Auto  F                      99.00                  8339.79
               M                      91.09                  7448.38
Special Auto   F                      92.31                  7691.58
               M                      86.34                  8247.09

                       Total Claim Amount
Policy Type    Gender
Corporate Auto F                   433.74
               M                   408.58
Personal Auto  F                   452.97
               M                   457.01
Special Auto   F                   453.28
               M                   429.53

In [10]:
customers_by_state = table_mkt.groupby("State")["Customer"].count()

customers_by_state

State
Arizona       1937
California    3552
Nevada         993
Oregon        2909
Washington     888
Name: Customer, dtype: int64

In [11]:
#FILTRAMOS LOS QUE TIENEN MAS DE 500

customers_by_state[customers_by_state > 500]

State
Arizona       1937
California    3552
Nevada         993
Oregon        2909
Washington     888
Name: Customer, dtype: int64

In [ ]:
#Máximo, mínimo y mediana de Customer Lifetime Value

In [12]:
table_mkt.groupby(["Education", "Gender"])

table_mkt.groupby(
    ["Education", "Gender"]
)["Customer Lifetime Value"]

In [13]:
clv_analysis = table_mkt.groupby(
    ["Education", "Gender"]
)["Customer Lifetime Value"].agg(
    ["max", "min", "median"]
)

In [14]:
clv_analysis = clv_analysis.round(2)

clv_analysis

                                  max      min   median
Education            Gender
Bachelor             F       73225.96  1904.00  5640.51
                     M       67907.27  1898.01  5548.03
College              F       61850.19  1898.68  5623.61
                     M       61134.68  1918.12  6005.85
Doctor               F       44856.11  2395.57  5332.46
                     M       32677.34  2267.60  5577.67
High School or Below F       55277.45  2144.92  6039.55
                     M       83325.38  1940.98  6286.73
Master               F       51016.07  2417.78  5729.86
                     M       50568.26  2272.31  5579.10

In [15]:
#EJERCICIO 5

table_mkt["Effective To Date"] = pd.to_datetime(
    table_mkt["Effective To Date"]
)

C:\Users\ASUS\AppData\Local\Temp\ipykernel_29416\1601930976.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  table_mkt["Effective To Date"] = pd.to_datetime(

In [16]:
table_mkt["Month"] = table_mkt["Effective To Date"].dt.month

In [17]:
policies_by_state_month = pd.pivot_table(
    table_mkt,
    index="State",
    columns="Month",
    values="Number of Policies",
    aggfunc="sum"
)

In [18]:
policies_by_state_month

Month          1     2
State
Arizona     3052  2864
California  5673  4929
Nevada      1493  1278
Oregon      4697  3969
Washington  1358  1225

In [19]:
#EJERICIO 6

#PRIMERO AGRUPAMOS POR MES Y ESTADO

policies_state_month = table_mkt.groupby(
    ["State", "Month"]
)["Number of Policies"].sum().reset_index()

In [20]:
top_states = (
    policies_state_month
    .groupby("State")["Number of Policies"]
    .sum()
    .sort_values(ascending=False)
    .head(3)
)

In [21]:
top_states_names = top_states.index

In [22]:
top_3 = policies_state_month[
    policies_state_month["State"].isin(top_states_names)]

In [23]:
top_3_table = pd.pivot_table(
    top_3,
    index="State",
    columns="Month",
    values="Number of Policies",
    aggfunc="sum",
    fill_value=0
)

top_3_table

Month          1     2
State
Arizona     3052  2864
California  5673  4929
Oregon      4697  3969